### ISSUE TITLE
Playback not as smooth when playing 4K Remux films compared to NFS

### ISSUE THREAD

**Issue by RHStonks** [pannal/plex-for-kodi#78]
Hi, I'm running the latest version of PlexMod 0.7.2 on Kodi 21 Omega beta 2  using Homatics Box R 4K Plus and I'm noticing playback is not smooth on 4K Remux films compared to NFS. There seems to be pauses in the video but no buffering circle has appeared. Playback using the official Plex app or NFS is fine. 

The PlexMod settings that I'm using:
Kodi buffer size - 512MB (Max setting)
Kodi Cache Readfactor - 50 (Max setting)

The Kodi Caching settings that I'm using under Kodi -> Settings -> Services -> Caching:
Buffer mode: Buffer all filesystems, including local files 
Memory Size: 512MB
Read Factor: 50x (Max Setting)
Chunk Size: 1MB

**Comment by pannal** [comment]
Good god, please read the descriptions of the cache settings in PM4K :D

Use ~100MB for the cache size and 1.5 for the readfactor (in Kodi Omega beta 2). Otherwise the new buffer handling _will_ lead to freezes and we pin your CPU.

**Comment by pannal** [comment]
PM4K should give you a recommended setting for the readfactor - it should say 1.5-4 for your Kodi version, does it? (Not sure which exact Kodi commit you're on)

**Comment by pannal** [comment]
You might also be running into other issues that should be fixed with 0.7.3, but that readfactor is crazy

**Comment by RHStonks** [comment]
I couldn't set the Kodi Cache size to 100MB so I've set it to 96MB which was the closest to 100MB with a read factor of 1.5. 

Still experiencing the same issue with 4K Remux films where playback is not smooth and experiencing pauses in the video (no buffering circle). 

No issues with playback on NFS. Any reason why that might be the case?

**Comment by pannal** [comment]
Maybe, it's a completely different stream compared to NFS - we're using the DirectPlay streaming endpoint of the Plex Server (via HTTP/HTTPS).

**Comment by pannal** [comment]
You can try to see whether using Kodi stable (20) changes this (then you'll need readfactor 5 at least). You can also post your PM4K DEBUG logs, maybe I can find something obvious.

**Comment by pannal** [comment]
There's possibly [someone with a similar issue](https://forums.plex.tv/t/plexmod-for-kodi-18-19-20-21/481208/892). Can you try going back to 0.7.1-rev4 to see whether the issue goes away?

**Comment by RHStonks** [comment]
Still the same issue with 4K Remux films with 0.7.1 rev 4. 

I can send debug logs to you. How do I enable and where do I view and send them to you?

**Comment by pannal** [comment]
Oh, interesting. You can just enable them in the addon settings (ideally externally by holding SELECT on the addon icon, settings), then send me your Kodi log.

**Comment by RHStonks** [comment]
I've enabled Debug Logging on the Plex addon. Where do I go now?

**Comment by pannal** [comment]
Well, you reproduce your issues and then navigate to where your kodi.log is, and post that. https://kodi.wiki/view/Log_file

**Comment by RHStonks** [comment]
If I enable Debug Logging on Plex addon settings do I also need to enable debug logging under Kodi -> settings -> systen -> logging?

**Comment by pannal** [comment]
AFAIK not, no. Only if you want to show the Kodi player internal logs. Shouldn't hurt, though.

**Comment by RHStonks** [comment]
Hi, I have a Kodi log link. Is it possible to email you the Kodi log link instead?

**Comment by RHStonks** [comment]
> AFAIK not, no. Only if you want to show the Kodi player internal logs. Shouldn't hurt, though.

I have a Kodi log link. Is it possible to email you the Kodi log link instead?

**Comment by pannal** [comment]
Better would be for me to DM it to me in [the Plex forum](https://forums.plex.tv/t/plexmod-for-kodi-18-19-20-21/481208/911).

**Comment by pannal** [comment]
Thanks for the log. The only thing I can see is a Kodi warning `CVideoPlayerAudio::Process - stream stalled` during playback, which is probably what you're experiencing.

That might be an indication for the Plex server not being able to send the data in a timely fashion (remember, it's sent via HTTP stream); check the Plex Server DEBUG log for issues. 

Or, more likely, the way Kodi handles streams on your particular TV box. Remember: Once we're handing off the stream URL to the Kodi player, it's out of our hands. PM4K doesn't handle playback, it's "just" a massive UI in a nutshell (not completely true, but for this situation it is).

There's many references to this:
https://discourse.coreelec.org/t/solved-cvideoplayeraudio-process-stream-stalled/1071
https://discourse.osmc.tv/t/cvideoplayeraudio-process-stream-stalled/90691
https://forum.kodi.tv/showthread.php?tid=341038
https://github.com/croneter/PlexKodiConnect/issues/1113

Nothing I can really help with.

**Comment by RHStonks** [comment]
Just reading that first link mentions that CoreELEC have increase the dynamic buffer so I may have to try a CoreELEC version instead to see if the issue resolves.

**Comment by pannal** [comment]
What are you using currently? The fix mentioned in the first link might just work for your box as well.

**Comment by RHStonks** [comment]
Homatics Box R 4K Plus using the Kodi 21 Omega Beta 2

**Comment by pannal** [comment]
Yes but what kind of operating system/Kodi build does it use?

**Comment by RHStonks** [comment]
> Yes but what kind of operating system/Kodi build does it use?

Android TV 12 beta

**Comment by pannal** [comment]
And what kind of Kodi are you running? Is there an option for you to run coreelec?

Android has its own issues.

**Comment by RHStonks** [comment]
Just running the quietvoid Kodi 21 Omega Beta 2. 

My box can run CoreELEC but I don't have a spare USB I can use. Will have to buy one. 

I had a look at the first link that you mentioned and I have to setup System.Exec(exec) but I've been looking online on trying to find a simple guide on setting it up on Android but the instructions aren't clear on how to do it.

**Comment by pannal** [comment]
I can't help you any further I'm afraid. I'm using Kodi on Windows to develop and an NVIDIA SHIELD daily. Never touched Coreelec/Libreelec.

**Comment by RHStonks** [comment]
I was able to buy a USB and install CoreELEC and this problem has been fixed. No issues with playing 4K Remux files on PlexMod using CoreELEC.
